#!/bin/sh
# vim: set ts=4 sw=4:
set -euo pipefail

apfs_cntr_limits() {
	local part_dev="$1"
	local key="$2"

	diskutil apfs resizeContainer "$part_dev" limits -plist | plutil -extract "$key" raw -
}

b2gb() {
	echo "$(( $1 / 1024 / 1024 / 1024 ))"
}

fs_type() {
	local mount_point="$1"

	diskutil info -plist "$mount_point" | plutil -extract FilesystemType raw -
}

fs_resize_if_needed() {
	local mount_point="$1"
	local cntr_dev phy_dev cur_size max_size

	cntr_dev="$(diskutil info -plist / | plutil -extract ParentWholeDisk raw -)"
	part_dev="$(diskutil info -plist "$cntr_dev" \
		| plutil -extract APFSPhysicalStores.0.APFSPhysicalStore raw -)"
	phy_dev="${part_dev%s[0-9]}"

	cur_size="$(apfs_cntr_limits "$part_dev" CurrentSize)"
	max_size="$(apfs_cntr_limits "$part_dev" MaximumSize)"

	if [ "$max_size" -ne "$cur_size" ]; then
		echo "Resizing $cntr_dev on $phy_dev from $(b2gb $cur_size) to $(b2gb $max_size) GiB" >&2

		echo yes | diskutil repairDisk "$phy_dev"
		diskutil apfs resizeContainer "/dev/$cntr_dev" 0
	fi
}


if [ "$(fs_type '/')" != 'apfs' ]; then
	echo "WARN: Filesystem $(fs_type '/') is not supported, skipping grow-fs" >&2
	return 0
fi

fs_resize_if_needed '/'
